spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankingproject
    username: root
    password: LeoMessi@10
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true 
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"     